printWidth: 120
tabWidth: 2
useTabs: true
singleQuote: false
semi: true
bracketSpacing: true
arrowParens: always
trailingComma: none
jsxSingleQuote: false
bracketSameLine: false
plugins:
  - prettier-plugin-tailwindcss
